import Foundation

// Minimal models used by the skeleton
struct Token: Codable {
    var accessToken: String
    var refreshToken: String?
    var expiresAt: TimeInterval
    var scope: String?
    var tokenType: String?

    enum CodingKeys: String, CodingKey {
        case accessToken = "access_token"
        case refreshToken = "refresh_token"
        case expiresAt = "expires_at"
        case scope
        case tokenType = "token_type"
    }
}

struct Track: Identifiable, Codable {
    var id: String
    var name: String
    var artistIds: [String]
    var artistNames: [String]
    var albumName: String?
    var releaseDate: String?
    var uri: String

    /// Backward-compatible initializer (releaseDate defaults to nil).
    init(id: String, name: String, artistIds: [String], artistNames: [String], albumName: String?, uri: String) {
        self.id = id
        self.name = name
        self.artistIds = artistIds
        self.artistNames = artistNames
        self.albumName = albumName
        self.releaseDate = nil
        self.uri = uri
    }

    init(id: String, name: String, artistIds: [String], artistNames: [String], albumName: String?, releaseDate: String?, uri: String) {
        self.id = id
        self.name = name
        self.artistIds = artistIds
        self.artistNames = artistNames
        self.albumName = albumName
        self.releaseDate = releaseDate
        self.uri = uri
    }

    /// Returns the decade string like "1980s", "2010s", or nil if unknown.
    var decade: String? {
        guard let dateStr = releaseDate,
              let year = Int(dateStr.prefix(4)),
              year >= 1900, year <= 2099
        else { return nil }
        let decadeStart = (year / 10) * 10
        return "\(decadeStart)s"
    }
}

struct Artist: Codable {
    var id: String
    var name: String
    var genres: [String]
}

struct Playlist: Identifiable, Codable {
    var id: String
    var name: String
}

struct GenreGroup: Identifiable {
    var id: String { name }
    var name: String
    var tracks: [Track]
    var mappedPlaylistId: String?
}

enum GroupingMode: String, CaseIterable, Identifiable {
    case genreOnly = "Genre Only"
    case genreAndDecade = "Genre + Decade"
    var id: String { rawValue }
}

// MARK: - Playlist Filters

/// Rules that define what kind of songs belong in a playlist.
/// Used for auto-sorting liked songs into the right playlist.
struct PlaylistFilter: Codable, Identifiable {
    var id: String { playlistId }
    var playlistId: String
    var playlistName: String
    var genres: [String]           // genres that belong in this playlist
    var decades: [String]          // e.g. ["1990s", "2000s"]
    var matchMode: MatchMode       // how to combine genre + decade filters

    enum MatchMode: String, Codable, CaseIterable {
        case anyGenre = "Any Genre"         // song matches if ANY genre matches
        case allGenres = "All Genres"       // song matches if ALL its genres are in the filter
        case genreAndDecade = "Genre + Decade" // must match both a genre and a decade
    }

    /// Returns true if the given track (with its artist genres) matches this filter.
    func matches(track: Track, trackGenres: [String]) -> Bool {
        let genreMatch: Bool
        let decadeMatch: Bool

        if genres.isEmpty {
            genreMatch = true
        } else {
            let trackGenreSet = Set(trackGenres.map { $0.lowercased() })
            let filterGenreSet = Set(genres.map { $0.lowercased() })
            switch matchMode {
            case .anyGenre, .genreAndDecade:
                genreMatch = !trackGenreSet.intersection(filterGenreSet).isEmpty
            case .allGenres:
                genreMatch = filterGenreSet.isSubset(of: trackGenreSet)
            }
        }

        if decades.isEmpty {
            decadeMatch = true
        } else {
            decadeMatch = track.decade.map { decades.contains($0) } ?? false
        }

        switch matchMode {
        case .anyGenre, .allGenres:
            return genreMatch
        case .genreAndDecade:
            return genreMatch && decadeMatch
        }
    }
}

/// A recommendation for filter settings on a playlist, generated by analyzing its contents.
struct FilterRecommendation: Identifiable {
    var id: String { playlistId }
    var playlistId: String
    var playlistName: String
    var topGenres: [(genre: String, percentage: Double)]   // sorted by frequency
    var topDecades: [(decade: String, percentage: Double)]
    var suggestedFilter: PlaylistFilter

    /// Human-readable summary of the recommendation.
    var summary: String {
        let genreStr = topGenres.prefix(3).map { "\($0.genre) (\(Int($0.percentage))%)" }.joined(separator: ", ")
        let decadeStr = topDecades.prefix(2).map { "\($0.decade) (\(Int($0.percentage))%)" }.joined(separator: ", ")
        var parts: [String] = []
        if !genreStr.isEmpty { parts.append("Genres: \(genreStr)") }
        if !decadeStr.isEmpty { parts.append("Decades: \(decadeStr)") }
        return parts.joined(separator: " | ")
    }
}

/// Result of routing a song: which playlist(s) it should go to.
struct SortResult: Identifiable {
    var id: String { track.id }
    var track: Track
    var matchedPlaylists: [(playlist: Playlist, filter: PlaylistFilter)]
    var isUnsorted: Bool { matchedPlaylists.isEmpty }
}
